version: "3.3"
services:
  app:
    container_name: app
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development

  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - "52000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - cv-builder-data:/var/lib/mysql

  adminer:
    links:
      - db
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  cv-builder-data: